### PR TITLE
add ability to read hdf5 embeddings from llm

### PR DESCRIPTION
**Pull request by f-hafner**
This is a work in progress to update the evaluation scripts with regards to #50 

@dakota0064 , I am currently subsampling from the hdf5 file. ~~will this break the evaluation report? if it does, for running the evalution with the existing code, is there any other way than loading *all* embeddings into memory?~~
do I need to change anything else to run the evaluation on the new embedding sets?

### CODE REVIEW

**Review by dakota0064 — APPROVED** [review]

**Comment by f-hafner** [comment]
[3e5070d](https://github.com/odissei-lifecourse/life-sequencing-dutch/pull/52/commits/3e5070d48d3237ea6e55fff1a8ae43ca403926b8) fixes part of #54

**Comment by f-hafner** [comment]
@dakota0064 , can we fix or remove those tests from `report_tests.py` that are failing everywhere? I think the overlap check for marriage.

**Comment by f-hafner** [comment]
I tried to randomly sample the rows to read, but I think hdf5 format is not efficient for this. instead, I'm loading the first `sample_size` rows of embeddings.
This is ok as long as the order in which the embeddings are stored is random. Currently this is the case because embeddings are computed from the training set, which was shuffled.

One alternative would be a sql-type database where (I think) any indexed row can be accessed with O(1), if the key is known.

**Comment by f-hafner** [comment]
This PR adds 
- reading embeddings from HDF5 files, including option to read all rows or only the first N rows in the file
- tests that the inputs to the report generation have correct types and shapes
- updated scripts to generate the income baseline for each year from INPATAB, and the ability to choose which year the baseline prediction for income should use

**Comment by f-hafner** [comment]
important add-on: the embeddings were not computed from the shuffled training set, because the training set is mlm-encoded, while the input data for inference were not mlm encoded.
I think in the current state, the data are indeed properly randomized because the non-mlm encoded dataset was created from the shuffled json file, but I am not 100% sure anymore.

**Pull request merged**
